version: 2

sources:
  - name: champions_league
    schema: football_data
    tables:
      - name: raw_cl__matches

  - name: european_championship
    schema: football_data
    tables:
      - name: raw_ec__matches

  - name: serie_a
    schema: football_data
    tables:
      - name: raw_sa__matches

  - name: premier_league
    schema: football_data
    tables:
      - name: raw_pl__matches

  - name: bundesliga
    schema: football_data
    tables:
      - name: raw_bl1__matches

  - name: eredivisie
    schema: football_data
    tables:
      - name: raw_ded__matches

  - name: campeonato_brasileiro
    schema: football_data
    tables:
      - name: raw_bsa__matches

  - name: primera_division
    schema: football_data
    tables:
      - name: raw_pd__matches

  - name: ligue_1
    schema: football_data
    tables:
      - name: raw_fl1__matches

  - name: championship
    schema: football_data
    tables:
      - name: raw_elc__matches

  - name: primeira_liga
    schema: football_data
    tables:
      - name: raw_ppl__matches

  - name: world_cup
    schema: football_data
    tables:
      - name: raw_wc__matches
