version: 2

sources:
  - name: champions_league
    schema: football_data
    tables:
      - name: raw_cl__matches

  - name: european_championship
    schema: football_data
    tables:
      - name: raw_ec__matches