-- mart table for BI visualization based on team_stats model
select

  season_id,
  season_year,
  match_id,
  match_date,
  matchday,
  global_matchday,
  team_id,
  team_name,
  matches_played,
  wins,
  losses,
  draws,
  points,
  home_pts,
  away_pts,
  goals_scored,
  goals_conceded,
  goal_difference,
  goals_scored_home,
  goals_conceded_home,
  goals_scored_away,
  goals_conceded_away,
  home_matches_played,
  away_matches_played,
  home_wins,
  home_draws,
  home_losses,
  away_wins,
  away_draws,
  away_losses,
  home_comebacks,
  away_comebacks,
  home_collapses,
  away_collapses

from {{ ref("int_sa__team_match_facts") }}
